"""empty message

Revision ID: 44b3e5bde4c0
Revises: b8edd92d46e7
Create Date: 2020-03-06 15:49:31.140251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44b3e5bde4c0'
down_revision = 'b8edd92d46e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_securities', sa.Column('trade_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlist_securities', 'trade_date')
    # ### end Alembic commands ###
