"""empty message

Revision ID: ac98739c7dd8
Revises: 
Create Date: 2020-03-14 12:15:48.926767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac98739c7dd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('available_securities',
    sa.Column('name', sa.String(length=70), nullable=True),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=40), nullable=True),
    sa.Column('benchmark_index', sa.String(length=30), nullable=True),
    sa.Column('ISO_alpha3_codes', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('login_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=257), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_details_username'), 'login_details', ['username'], unique=True)
    op.create_table('sector_definitions',
    sa.Column('name', sa.String(length=70), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_sector_definitions_name'), 'sector_definitions', ['name'], unique=False)
    op.create_table('watchlist_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['login_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watchlist_securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist', sa.String(length=25), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('trade_date', sa.DateTime(), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.Column('comments', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['watchlist_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['login_details.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_securities_id'), 'watchlist_securities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_securities_id'), table_name='watchlist_securities')
    op.drop_table('watchlist_securities')
    op.drop_table('watchlist_group')
    op.drop_index(op.f('ix_sector_definitions_name'), table_name='sector_definitions')
    op.drop_table('sector_definitions')
    op.drop_index(op.f('ix_login_details_username'), table_name='login_details')
    op.drop_table('login_details')
    op.drop_table('available_securities')
    # ### end Alembic commands ###
